### ISSUE TITLE
android.view.InflateException: Binary XML file line #10: Error inflating class 

### ISSUE THREAD

**Issue by mathiasconradt** [johannilsson/android-pulltorefresh#12]
I cloned the master branch and run it, but get an inflation exception as below. Running it on 2.2:

05-17 18:14:26.604: ERROR/AndroidRuntime(361): FATAL EXCEPTION: main
        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.markupartist.android.example.pulltorefresh/com.markupartist.android.example.pulltorefresh.PullToRefreshActivity}: android.view.InflateException: Binary XML file line #10: Error inflating class com.markupartist.android.widget.PullToRefreshListView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2663)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2679)
        at android.app.ActivityThread.access$2300(ActivityThread.java:125)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:123)
        at android.app.ActivityThread.main(ActivityThread.java:4627)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:521)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
        at dalvik.system.NativeStart.main(Native Method)
        Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class com.markupartist.android.widget.PullToRefreshListView
        at android.view.LayoutInflater.createView(LayoutInflater.java:513)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:565)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:618)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:407)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:198)
        at android.app.Activity.setContentView(Activity.java:1647)
        at com.markupartist.android.example.pulltorefresh.PullToRefreshActivity.onCreate(PullToRefreshActivity.java:21)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2627)
        ... 11 more
        Caused by: java.lang.reflect.InvocationTargetException
        at com.markupartist.android.widget.PullToRefreshListView.<init>(PullToRefreshListView.java:54)
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:446)
        at android.view.LayoutInflater.createView(LayoutInflater.java:500)
        ... 21 more
        Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f030002
        at android.content.res.Resources.getValue(Resources.java:892)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:1869)
        at android.content.res.Resources.getLayout(Resources.java:731)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:318)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
        at com.markupartist.android.widget.PullToRefreshListView.init(PullToRefreshListView.java:80)
        ... 25 more

**Comment by johannilsson** [comment]
Make sure that it's setup as a [library project](http://developer.android.com/guide/developing/projects/projects-eclipse.html#SettingUpLibraryProject), if you're using Eclipse you might need to do clean on both the example project and the library project.

**Comment by mathiasconradt** [comment]
Thanks, yes got it working now. Some project dependency settings were wrong in IntelliJ. Was a bit confused by the @+id/android:list, instead of (@id/android:list), why there was a + in it, so I first dumped everything into one project. But it seems to work ok anyhow. Closing this one.

**Comment by johannilsson** [comment]
Happy to hear, you're right the `+` is not needed for lists.

**Comment by sahib20** [comment]
i try all way but it still  give an error. how to resolve this. please give brief example or solution. why it should give error in list fragment.
